# Generated by Django 3.1.4 on 2020-12-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('pizzas', models.ManyToManyField(blank=True, to='order.Pizza')),
            ],
        ),
    ]
