# Generated by Django 3.1.4 on 2020-12-12 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20201212_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='price',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='size',
        ),
        migrations.CreateModel(
            name='ToppingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Basic Toppings', 'Basic Toppings'), ('Deluxe Toppings', 'Deluxe Toppings')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.size')),
            ],
        ),
        migrations.AlterField(
            model_name='topping',
            name='topping_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.toppingtype'),
        ),
    ]
