# Generated by Django 3.1.4 on 2020-12-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20201212_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppingtype',
            name='price',
        ),
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
