# Generated by Django 3.1.4 on 2020-12-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20201214_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='price',
        ),
        migrations.AddField(
            model_name='toppingtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
